vaadin.launch-browser=true
spring.application.name=photo-act

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=145MB
spring.servlet.multipart.max-request-size=155MB

#vaadin.allowed-packages = com.vaadin,org.vaadin,dev.hilla,com.flowingcode
vaadin.allowed-packages = com.vaadin,org.vaadin,dev.hilla,com.flowingcode

spring.datasource.url=jdbc:mariadb://photoact.net:3306/journey?serverTimezone=Europe/Athens
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=adminbe
spring.datasource.password=ameli23330.ameli.24459
