spring.application.name=photoact

server.tomcat.remoteip.protocol-header=X-Real-IP
# https://runebook.dev/en/articles/spring_boot/application-properties/application-properties.server.server.tomcat.remoteip.protocol-header

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=16MB
spring.servlet.multipart.file-size-threshold = 4MB

#spring.servlet.multipart.max-file-size=22MB
#spring.servlet.multipart.max-request-size=32MB

spring.devtools.add-properties = false
logging.level.org.atmosphere = warn
#logging.level.web = DEBUG

spring.mustache.check-template-location=false
spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.username=info@photoact.net
spring.mail.password=Ameli.76.Ameli
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.debug=true

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=true
# To improve the performance during development.
# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
# https://vaadin.com/docs/latest/flow/integrations/spring/configuration
vaadin.allowed-packages=com.vaadin,org.vaadin,dev.hilla,com.flowingcode,com.storedobject,com.github.appreciated
vaadin.exclude-urls=/swagger-ui/**,/api/**,/actuator/**,/actuator/health/**
spring.datasource.url=jdbc:mariadb://localhost:3306/journey?serverTimezone=Europe/Athens
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=adminbe
spring.datasource.password=ameli23330.ameli.24459
#Redis as Cache
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
#spring.data.redis.url=redis://:2333026975@localhost:6379
spring.cache.redis.time-to-live=8h
spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){black} %clr(%-40.40logger{0}){blue} %clr(:){black} %clr(%m){faint}%n

