vaadin.launch-browser=true
spring.application.name=photoact

server.tomcat.remoteip.protocol-header=X-Real-IP
# https://runebook.dev/en/articles/spring_boot/application-properties/application-properties.server.server.tomcat.remoteip.protocol-header

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size = 15MB
spring.servlet.multipart.max-request-size = 21MB
spring.servlet.multipart.file-size-threshold = 4MB
#spring.servlet.multipart.max-file-size=22MB
#spring.servlet.multipart.max-request-size=32MB


spring.devtools.add-properties = false
logging.level.org.atmosphere = warn
#logging.level.web = DEBUG


spring.mustache.check-template-location=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ngiant@gmail.com
spring.mail.password=iuks yhps ljhe uauz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#vaadin.allowed-packages = com.vaadin,org.vaadin,dev.hilla,com.flowingcode
vaadin.allowed-packages = com.vaadin,org.vaadin,dev.hilla,com.flowingcode

spring.datasource.url=jdbc:mariadb://localhost:3306/journey
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=adminbe
spring.datasource.password=ameli23330.ameli.24459
